---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-ns-purger
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8s-ns-purger
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8s-ns-purger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-ns-purger
subjects:
- kind: ServiceAccount
  name: k8s-ns-purger
  namespace: kube-system
