---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-ns-purger
  name: k8s-ns-purger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-ns-purger
  template:
    metadata:
      labels:
        app: k8s-ns-purger
    spec:
      serviceAccountName: k8s-ns-purger
      containers:
      - image: supporttools/k8s-ns-purger:BUILD_NUMBER
        imagePullPolicy: IfNotPresent
        name: k8s-ns-purger
