name: Test, Build, and Publish

on:
  push:
    branches:
      - main

jobs:
  test-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Run tests
        run: |
          go test -v ./...
          go test -cover ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --pull \
            --build-arg VERSION=v${{ github.run_number }} \
            --build-arg GIT_COMMIT=${{ github.sha }} \
            --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
            --cache-from=type=registry,ref=supporttools/k8s-ns-purger:latest \
            --cache-to=type=inline \
            -t supporttools/k8s-ns-purger:v${{ github.run_number }} \
            -t supporttools/k8s-ns-purger:latest \
            --push \
            -f Dockerfile .

      - name: Verify image in DockerHub
        run: |
          echo "Verify the image has been pushed successfully."
          docker pull supporttools/k8s-ns-purger:latest
          docker images | grep supporttools/k8s-ns-purger

  publish-helm-chart:
    runs-on: ubuntu-latest
    needs: test-build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Helm Lint
        run: helm lint charts/k8s-ns-purger/

      - name: Package Helm chart
        run: |
          export CHART_VERSION="v${{ github.run_number }}"
          export APP_VERSION="v${{ github.run_number }}"
          export IMAGE_TAG="v${{ github.run_number }}"
          echo "CHART_VERSION=${CHART_VERSION}"
          echo "APP_VERSION=${APP_VERSION}"
          envsubst < charts/k8s-ns-purger/Chart.yaml.template > charts/k8s-ns-purger/Chart.yaml
          envsubst < charts/k8s-ns-purger/values.yaml.template > charts/k8s-ns-purger/values.yaml
          helm package charts/k8s-ns-purger --destination helm/repo

      - name: Checkout helm-chart repository
        uses: actions/checkout@v2
        with:
          repository: supporttools/helm-chart
          path: helm-chart
          token: ${{ secrets.BOT_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Action"

      - name: Update Helm repository
        run: |
          cp helm/repo/k8s-ns-purger-*.tgz helm-chart/
          cd helm-chart
          helm repo index . --url https://charts.support.tools/
          git add .
          git commit -m "Update Helm chart for k8s-ns-purger"
          git push
